spring:
  datasource:
    platform: h2
    data: "classpath:customer.sql"
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
logging:
  level:
    root: warn
    org:
      hibernate: info