server:
  port: 7007
spring:
  application:
    name: user-module
  profiles:
    active: dev
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
    fetch-registry: true
    register-with-eureka: true
