spring:
  application:
    name: zull-gateway
  profiles:
    active: dev
  devtools:
    livereload:
      enabled: true

server:
  port: 7006
zuul:
  routes:
    web-app:
      path: /app/**
      url: http://localhost:7003/
    web-mobile:
      path: /mobile/**
      url: http://localhost:7005/
    user-module:
      path: /user/**
      url: http://localhost:7007/

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
    fetch-registry: true
    register-with-eureka: true
